using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ActivityRecommendation
{
    public abstract class Rating
    {
        public abstract Rating MakeCopy();

        public void CopyFrom(Rating original)
        {
            this.Source = original.Source;
        }
        public RatingSource Source { get; set; }

        // adds any additional data based on the fact that this rating was generated by the given Participation
        public virtual void FillInFromParticipation(Participation participation)
        {
            this.Source = RatingSource.Participation;
        }
        // adds any additional data based on the fact that this rating was generated by the given Skip
        public virtual void FillInFromSkip(ActivitySkip skip)
        {
            this.Source = RatingSource.Skip;
        }
        // adds any additional data based on the fact that this rating was generated by the given ActivityRequest
        public virtual void FillInFromRequest(ActivityRequest request)
        {
            this.Source = RatingSource.Request;
        }
    }
}
